# pytest.ini

[pytest]
markers =
    asyncio: mark a test as asyncio.

filterwarnings =
    ignore::Warning

log_cli = true
log_cli_level = DEBUG
log_cli_format = %(asctime)s | %(levelname)-8s | %(name)s:%(funcName)s:%(lineno)d - %(message)s
log_cli_date_format = %H:%M:%S